from nose.tools import eq_, ok_

import gold_standard_src.gold_standard.aln_processor as ap


def test_find_positions_to_fill_in():
    aln_dict = {
            "4FDXA":  "PIIQMNLLEGRTVEQKRNAVAAITEAVVRTLDVRPDQVRILINELGVEHFSVAGQTAAMRQ",
            "3RY0A":  "PLIRVTLLEGRSPQEVAALGEALTAAAHETLGTPVEAVRVIVEETPPERWFVGGRSVAERR",
            "4X1CH":  "PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKV-",
            "1MWWA":  "TVIEINLMAGRMEGTKKRLIKMLFSELEYKLGIRAHDVEITIKEQPAHCWGFRGMTG--EA",
            "3M21A":  "PFINIKLVpgPTNEQKQQLIEGVSDLMVKVLNKNKASIVVIIDEVDSNNYGLGGESVHHLR",
            "4FAZA":  "PFAQIYLIEGRTEEQKRAVIEKVTQAMMEAVGAPKENVRVWIHDVPKENWGIGGVSAKALG",
            "3MB2A":  "LLLRITMLEGRSTEQKAELARALSAAAAAAFDVPLAEVRLIIQEVPPTHWTVGGISMA-EL",
            "1OTFA":  "PIAQLYIIEGRTDEQKETLIRQVSEAMANSLDAPLERVRVLITEMPKNHFGIGGEPASK--",
            "2OPAA":  "PYVTVKMLEGRTDEQKRNLVEKVTEAVKETTGASEEKIVVFIEEMRKDHYAVAGKRLSDME",
    }
    aln_dict = {
        "4FDXA":  "PIIQMNLLEGRTVEQKRNAVAAITEAVVRTLDVRPDQVRILINELGVEHFSVAGQTAAMr",
        "3RY0A":  "PLIRVTLLEGRSPQEVAALGEALTAAAHETLGTPVEAVRVIVEETPPERWFVGGRSVAEr",
        "4X1CH":  "PIAQIHILEGRSDEQKETLIREVSEAISRSLDapLTSVRVIITEMAKGHFGIGGELASKv",
        "1MWWA":  "TVIEINLMAGRMEGTKKRLIKMLFSELEYKLGIRAHDVEITIKEQPAHCWGFRGMTG--e",
        "3M21A":  "PFINIKLVpgPTNEQKQQLIEGVSDLMVKVLNKNKASIVVIIDEVDSNNYGLGGESVHHl",
        "4FAZA":  "PFAQIYLIEGRTEEQKRAVIEKVTQAMMEAVGAPKENVRVWIHDVPKENWGIGGVSAKAl",
        "3MB2A":  "LLLRITMLEGRSTEQKAELARALSAAAAAAFDVPLAEVRLIIQEVPPTHWTVGGISMA-e",
        "1OTFA":  "PIAQLYIIEGRTDEQKETLIRQVSEAMANSLDAPLERVRVLITEMPKNHFGIGGEPASK-",
        "2OPAA":  "PYVTVKMLEGRTDEQKRNLVEKVTEAVKETTGASEEKIVVFIEEMRKDHYAVAGKRLSDm",
    }

    master_full_seq = "PIAQIHILEGRSDEQKETLIREVSEAISRSLDASPLTSVRVIITEMAKGHFGIGGELASKVRA"
    master_aln_seq = aln_dict["4X1CH"]

    positions_to_fill_in = ap.find_positions_to_fill_in(master_full_seq, master_aln_seq)
    eq_(positions_to_fill_in, [(33, 'S'), (60, 'R'), (60, 'A')])
    # eq_(positions_to_fill_in, [(33, 'S'), (60, 'R'), (61, 'A')])


def test_fill_in_gaps():
    aln_dict = {
        "4X1CH":  "PIAQIHILEGRSDEQKETLIREVSEAISRSLDapLTSVRVIITEMAKGHFGIGGELASKv",
        "4FDXA":  "PIIQMNLLEGRTVEQKRNAVAAITEAVVRTLDVRPDQVRILINELGVEHFSVAGQTAAMr",
        "3RY0A":  "PLIRVTLLEGRSPQEVAALGEALTAAAHETLGTPVEAVRVIVEETPPERWFVGGRSVAEr",
        "1MWWA":  "TVIEINLMAGRMEGTKKRLIKMLFSELEYKLGIRAHDVEITIKEQPAHCWGFRGMTG--e",
        "3M21A":  "PFINIKLVpgPTNEQKQQLIEGVSDLMVKVLNKNKASIVVIIDEVDSNNYGLGGESVHHl",
        "4FAZA":  "PFAQIYLIEGRTEEQKRAVIEKVTQAMMEAVGAPKENVRVWIHDVPKENWGIGGVSAKAl",
        "3MB2A":  "LLLRITMLEGRSTEQKAELARALSAAAAAAFDVPLAEVRLIIQEVPPTHWTVGGISMA-e",
        "1OTFA":  "PIAQLYIIEGRTDEQKETLIRQVSEAMANSLDAPLERVRVLITEMPKNHFGIGGEPASK-",
        "2OPAA":  "PYVTVKMLEGRTDEQKRNLVEKVTEAVKETTGASEEKIVVFIEEMRKDHYAVAGKRLSDm",
    }

    master_full_seq = "PIAQIHILEGRSDEQKETLIREVSEAISRSLDASPLTSVRVIITEMAKGHFGIGGELASKVRA"
    master_id = "4X1CH"
    master_aln_seq = aln_dict[master_id]

    positions_to_fill_in = ap.find_positions_to_fill_in(master_full_seq, master_aln_seq)
    eq_(positions_to_fill_in, [(33, 'S'), (60, 'R'), (60, 'A')])

    ap.fill_in_gaps(aln_dict, positions_to_fill_in, master_id, master_full_seq)

    expected = {
        "4X1CH":  "PIAQIHILEGRSDEQKETLIREVSEAISRSLDASPLTSVRVIITEMAKGHFGIGGELASKVRA",
        "4FDXA":  "PIIQMNLLEGRTVEQKRNAVAAITEAVVRTLDV-RPDQVRILINELGVEHFSVAGQTAAMr--",
        "3RY0A":  "PLIRVTLLEGRSPQEVAALGEALTAAAHETLGT-PVEAVRVIVEETPPERWFVGGRSVAEr--",
        "1MWWA":  "TVIEINLMAGRMEGTKKRLIKMLFSELEYKLGI-RAHDVEITIKEQPAHCWGFRGMTG--e--",
        "3M21A":  "PFINIKLVpgPTNEQKQQLIEGVSDLMVKVLNK-NKASIVVIIDEVDSNNYGLGGESVHHl--",
        "4FAZA":  "PFAQIYLIEGRTEEQKRAVIEKVTQAMMEAVGA-PKENVRVWIHDVPKENWGIGGVSAKAl--",
        "3MB2A":  "LLLRITMLEGRSTEQKAELARALSAAAAAAFDV-PLAEVRLIIQEVPPTHWTVGGISMA-e--",
        "1OTFA":  "PIAQLYIIEGRTDEQKETLIRQVSEAMANSLDA-PLERVRVLITEMPKNHFGIGGEPASK---",
        "2OPAA":  "PYVTVKMLEGRTDEQKRNLVEKVTEAVKETTGA-SEEKIVVFIEEMRKDHYAVAGKRLSDm--",
    }

    # eq_(aln_dict, expected)
    for i, seq in expected.iteritems():
        eq_(seq, aln_dict[i])


def test_remove_positions():

    aln_dict = {
        "4X1CH":  "PIA-IHILEGRSDEQKETLIREVSEAISRSLDapLTSVRVIITEMAKGHFGIGGELASKV-",
        "4FDXA":  "PIIQMNLLEGRTVEQKRNAVAAITEAVVRTLDVRPDQVRILINELGVEHFSVAGQTAAMRQ",
        "3RY0A":  "PLIRVTLLEGRSPQEVAALGEALTAAAHETLGTPVEAVRVIVEETPPERWFVGGRSVAERR",
        "1MWWA":  "TVIEINLMAGRMEGTKKRLIKMLFSELEYKLGIRAHDVEITIKEQPAHCWGFRGMTG--EA",
        "3M21A":  "PFINIKLVpgPTNEQKQQLIEGVSDLMVKVLNKNKASIVVIIDEVDSNNYGLGGESVHHLR",
        "4FAZA":  "PFAQIYLIEGRTEEQKRAVIEKVTQAMMEAVGAPKENVRVWIHDVPKENWGIGGVSAKALG",
        "3MB2A":  "LLLRITMLEGRSTEQKAELARALSAAAAAAFDVPLAEVRLIIQEVPPTHWTVGGISMA-EL",
        "1OTFA":  "PIAQLYIIEGRTDEQKETLIRQVSEAMANSLDAPLERVRVLITEMPKNHFGIGGEPASK--",
        "2OPAA":  "PYVTVKMLEGRTDEQKRNLVEKVTEAVKETTGASEEKIVVFIEEMRKDHYAVAGKRLSDME",
    }

    master_id = "4X1CH"
    positions_to_remove = ap.find_positions_to_remove(aln_dict[master_id])
    ap.remove_positions(aln_dict, positions_to_remove)

    expected = {
        "4X1CH":  "PIaiHILEGRSDEQKETLIREVSEAISRSLDapLTSVRVIITEMAKGHFGIGGELASKv",
        "4FDXA":  "PIimNLLEGRTVEQKRNAVAAITEAVVRTLDVRPDQVRILINELGVEHFSVAGQTAAMr",
        "3RY0A":  "PLivTLLEGRSPQEVAALGEALTAAAHETLGTPVEAVRVIVEETPPERWFVGGRSVAEr",
        "1MWWA":  "TViiNLMAGRMEGTKKRLIKMLFSELEYKLGIRAHDVEITIKEQPAHCWGFRGMTG--e",
        "3M21A":  "PFiiKLVpgPTNEQKQQLIEGVSDLMVKVLNKNKASIVVIIDEVDSNNYGLGGESVHHl",
        "4FAZA":  "PFaiYLIEGRTEEQKRAVIEKVTQAMMEAVGAPKENVRVWIHDVPKENWGIGGVSAKAl",
        "3MB2A":  "LLliTMLEGRSTEQKAELARALSAAAAAAFDVPLAEVRLIIQEVPPTHWTVGGISMA-e",
        "1OTFA":  "PIalYIIEGRTDEQKETLIRQVSEAMANSLDAPLERVRVLITEMPKNHFGIGGEPASK-",
        "2OPAA":  "PYvvKMLEGRTDEQKRNLVEKVTEAVKETTGASEEKIVVFIEEMRKDHYAVAGKRLSDm",
    }

    eq_(aln_dict, expected)

    aln_dict = {
        "4X1CH":  "--PIAIHILE",
        "4FDXA":  "MSPIIMNLLE"
    }
    master_id = "4X1CH"
    positions_to_remove = ap.find_positions_to_remove(aln_dict[master_id])
    ap.remove_positions(aln_dict, positions_to_remove)
    expected = {
        "4X1CH":  "pIAIHILE",
        "4FDXA":  "pIIMNLLE"
    }
    eq_(aln_dict, expected)

def test_make_master_seq_full():
    # testcase 1: tautomerase
    aln_dict = {
        "4X1CH":  "PIA-IHILEGRSDEQKETLIREVSEAISRSLDapLTSVRVIITEMAKGHFGIGGELASKV-",
        "4FDXA":  "PIIQMNLLEGRTVEQKRNAVAAITEAVVRTLDVRPDQVRILINELGVEHFSVAGQTAAMRQ",
        "3RY0A":  "PLIRVTLLEGRSPQEVAALGEALTAAAHETLGTPVEAVRVIVEETPPERWFVGGRSVAERR",
        "1MWWA":  "TVIEINLMAGRMEGTKKRLIKMLFSELEYKLGIRAHDVEITIKEQPAHCWGFRGMTG--EA",
        "3M21A":  "PFINIKLVpgPTNEQKQQLIEGVSDLMVKVLNKNKASIVVIIDEVDSNNYGLGGESVHHLR",
        "4FAZA":  "PFAQIYLIEGRTEEQKRAVIEKVTQAMMEAVGAPKENVRVWIHDVPKENWGIGGVSAKALG",
        "3MB2A":  "LLLRITMLEGRSTEQKAELARALSAAAAAAFDVPLAEVRLIIQEVPPTHWTVGGISMA-EL",
        "1OTFA":  "PIAQLYIIEGRTDEQKETLIRQVSEAMANSLDAPLERVRVLITEMPKNHFGIGGEPASK--",
        "2OPAA":  "PYVTVKMLEGRTDEQKRNLVEKVTEAVKETTGASEEKIVVFIEEMRKDHYAVAGKRLSDME",
    }

    # can just give one (master/target) id and full sequence, these are the only
    # one needed in this function
    gold_ids = ["4X1CH"]
    full_seqs = {
     "4X1CH": "PIAQIHILEGRSDEQKETLIREVSEAISRSLDASPLTSVRVIITEMAKGHFGIGGELASKVRA"
    }

    expected = {
        "4X1CH":  "PIAQIHILEGRSDEQKETLIREVSEAISRSLDASPLTSVRVIITEMAKGHFGIGGELASKVRA",
        "4FDXA":  "PIi-mNLLEGRTVEQKRNAVAAITEAVVRTLDV-RPDQVRILINELGVEHFSVAGQTAAMr--",
        "3RY0A":  "PLi-vTLLEGRSPQEVAALGEALTAAAHETLGT-PVEAVRVIVEETPPERWFVGGRSVAEr--",
        "1MWWA":  "TVi-iNLMAGRMEGTKKRLIKMLFSELEYKLGI-RAHDVEITIKEQPAHCWGFRGMTG--e--",
        "3M21A":  "PFi-iKLVpgPTNEQKQQLIEGVSDLMVKVLNK-NKASIVVIIDEVDSNNYGLGGESVHHl--",
        "4FAZA":  "PFa-iYLIEGRTEEQKRAVIEKVTQAMMEAVGA-PKENVRVWIHDVPKENWGIGGVSAKAl--",
        "3MB2A":  "LLl-iTMLEGRSTEQKAELARALSAAAAAAFDV-PLAEVRLIIQEVPPTHWTVGGISMA-e--",
        "1OTFA":  "PIa-lYIIEGRTDEQKETLIRQVSEAMANSLDA-PLERVRVLITEMPKNHFGIGGEPASK---",
        "2OPAA":  "PYv-vKMLEGRTDEQKRNLVEKVTEAVKETTGA-SEEKIVVFIEEMRKDHYAVAGKRLSDm--",
    }
    result_dict = ap.make_master_seq_full(aln_dict, full_seqs, gold_ids, "4X1CH")

    eq_(result_dict, expected)

    # testcase 2: cupins - nothing to change
    aln_dict = {
        "4HN1A": "MHPLSIEGAWSQEPVIHSDHRGRSHEWFRGESFRQAFGHDFPVAQVNVAVSHRGALRGINYTEIPPGQAKYSVCVRGAGLDVVVDVRIGSPTFGRWEIVPMDAERNTAVYLTAGLGRAFLSLTDDATLVFLCSSGYAPAREHSVNPLDPDLGIAWPDDIEPLLSDRDENAPTLATAERLGLLPTYQAWQEQQQAQRLEH",
        "2C0ZA": "LRPLGIEGVWEITPEQRADPRGVFLDWYHVDRFAEAIGRPLRLAQANLSVSVRGVVRGIHFVDVPPGQAKYVTCVRGAVFDVVVDLRVGSPTYGCWEGTRLDDVSRRAVYLSEGIGHGFCAISDEATLCYLSSGTYDPATEHGVHPLDPELAIDWPTG-TPLLSPRDQDALLLAEARDAGLLPTY--------------",
        "2IXCB": "ARELDVPGAWEITPTIHVDSRGLFFEWLTDHGFRAFAGHSLDVRQVNCSVSSAGVLRGLHFAQLPPSQAKYVTCVSGSVFDVVVDIREGSPTFGRWDSVLLDDQDRRTIYVSEGLAHGFLALQDNSTVMYLCSAEYNPQREHTICATDPTLAVDWPlgAAPSLSDRDAAAPSFEDVRASGLLPRW--------------",
        "1OFNB": "ARKLAVDGAIEFTPRVFADDRGLLILPYQ-EefVEAHGGPL---QTIHSMSKRGVVRGIHYTVTPPGTAKYVYCARGKAMDIVIDIRVGSPTFGQWDSVLMDQQDPRAVYLPVGVGHAFVALEDDTVMSYMLSRSYVTQDELALSALDPALGLPIDIGVEPIVSDRDRVAITLAEAQRQGLLPDY--------------",
        "1EPZA": "FIKTSLDGAIIIEPEVYTDERGYFMETFNEAIFQEN----VRFVQDNESMSVRGVLRGLHFQR-EKPQGKLVRVIRGEIFDVAVDLRKNSDTYGEWTGVRLSDENRREFFIPEGFAHGFLALSDECIVNYKCTELYHPEYDSGIPWDDPDIGIDWPL--DLIISEKDRNWKPLRENP----------------------",
        "2IXKA": "ATRLAIPDVILFEPRVFGDDRGFFFESYNQRAFEEAchP-VSFVQDNHSRSARGVLRGLHYQI-RQAQGKLVRATLGEVFDVAVDLRRGSPTFGQWVGERLSAENKRQMWIPAGFAHGFVVLSEYAEFLYKTTDFWAPEHERCIVWNDPELKIDWPLQDAPLLSEKDRQGKAFADA----DCFP---------------",
        "3RYKB": "veTN---DAKLLEPRLFGDDRGFFTESYNKKVLEtgV--THSFVQDNVSYseAGTIRGLHFQKNPKAQTKLIQVMQGAIYDVIVDLRKDSPTFKQWRGYILSADNHRQLLVPKGFAHGFCTLVPHTIVMYKVDEYYSADHDSGVLWNDKELAIPWPV-TSPILSDKDRILPLL--------------------------",
        "1WLTA": "FENLG-MGIILIKPKVFPDKRGFFLEVFKSEDFTKMR---PNVIQTNMSFSRKGVVRGLHYQRTPKEQGKIIFVPKGRILDVAVDVRKSSPTFGKYVKAELNEENHYMLWIPPGFAHGFQALED-SIVIYFItnEYSPPHERCISYSY----IDWPI-KEVIISDKDLQCPSLEKA----EVFD---------------",
        "1NXMA": "ARPVeiPGMLEFDIPVHGDNRGWFKENFQKEKMLP-----FF-LQNNVSFSRKNVLRGLHAE----PWDKYISVagGKVLGTWVDLREG-ETFGNTYQTVIDA--SKSIFVPRGVANGFQVLSDFVAYSYLVNDY-------FVNYADPSLDIKWENLEEAEVSEADENHPFLKDVK----PLR---------------",
        "5BUVB": "ITELNISGCYLIESPIFSDERGEFVKTHHQEIFKNF------SAEEYYSRSKNNVIRGMHFQQYPDDHNKLVFCPEGEVLDVFLDIRKDSNTYGQFMSFILNPHNRRSIFLAKGIAHGFLSMKDNTLIVCKTSTVHSPSRDSGIHWNS--FGFKWPV-ENPIISDKDRNLDCF--------------------------",
        "2PA7A": "-EN------KVINFKKIIDSRGSLVA-IEE----------FSIKRVYYIftKGEEPRGFHAH----KLEQVLVCLNGSCRVILDD---------IIQEITLD--SpvGLYVGPAVWHEMHDFSSDCVMMVLASDYYDETDYIR-------------------------------------NF-----------------",
        "4O9GB": "----MLYNVALIKFKDIADKYGHLTP-IekI---------FDIKRVYYItvDKDITRGYNS-----KLHQVLICLNGSVKIRLKI-------PDEEKIIELN--DpvGLYIGPLVWREMFDFTEGCVLLVLASeyDETDYIRNY------------------------------------FY-----------------",
        "4ZU4A": "LQMSKVKGVSLHKFHLVNDLRGNLSV-GEF----------FTPKRYFTVfvPNKEVRGEHAH----ECKQFLICVSGNCSVLVDD-------GENREEYVLDS---KGIYLPPMTWGVQYKYSKDAVLLVFASHYYDSDDYIR-------------------------------------TF-----------------"
    }

    full_seqs = {
        "4HN1A": "MHPLSIEGAWSQEPVIHSDHRGRSHEWFRGESFRQAFGHDFPVAQVNVAVSHRGALRGINYTEIPPGQAKYSVCVRGAGLDVVVDVRIGSPTFGRWEIVPMDAERNTAVYLTAGLGRAFLSLTDDATLVFLCSSGYAPAREHSVNPLDPDLGIAWPDDIEPLLSDRDENAPTLATAERLGLLPTYQAWQEQQQAQRLEH"
    }

    result_dict = ap.make_master_seq_full(aln_dict, full_seqs, gold_ids, "4HN1A")
    eq_(result_dict["4HN1A"], full_seqs["4HN1A"])
    gold_ids = ["4HN1A"]

    expected = {
        "4HN1A": "MHPLSIEGAWSQEPVIHSDHRGRSHEWFRGESFRQAFGHDFPVAQVNVAVSHRGALRGINYTEIPPGQAKYSVCVRGAGLDVVVDVRIGSPTFGRWEIVPMDAERNTAVYLTAGLGRAFLSLTDDATLVFLCSSGYAPAREHSVNPLDPDLGIAWPDDIEPLLSDRDENAPTLATAERLGLLPTYQAWQEQQQAQRLEH",
        "2C0ZA": "LRPLGIEGVWEITPEQRADPRGVFLDWYHVDRFAEAIGRPLRLAQANLSVSVRGVVRGIHFVDVPPGQAKYVTCVRGAVFDVVVDLRVGSPTYGCWEGTRLDDVSRRAVYLSEGIGHGFCAISDEATLCYLSSGTYDPATEHGVHPLDPELAIDWPTG-TPLLSPRDQDALLLAEARDAGLLPTY--------------",
        "2IXCB": "ARELDVPGAWEITPTIHVDSRGLFFEWLTDHGFRAFAGHSLDVRQVNCSVSSAGVLRGLHFAQLPPSQAKYVTCVSGSVFDVVVDIREGSPTFGRWDSVLLDDQDRRTIYVSEGLAHGFLALQDNSTVMYLCSAEYNPQREHTICATDPTLAVDWPlgAAPSLSDRDAAAPSFEDVRASGLLPRW--------------",
        "1OFNB": "ARKLAVDGAIEFTPRVFADDRGLLILPYQ-EefVEAHGGPL---QTIHSMSKRGVVRGIHYTVTPPGTAKYVYCARGKAMDIVIDIRVGSPTFGQWDSVLMDQQDPRAVYLPVGVGHAFVALEDDTVMSYMLSRSYVTQDELALSALDPALGLPIDIGVEPIVSDRDRVAITLAEAQRQGLLPDY--------------",
        "1EPZA": "FIKTSLDGAIIIEPEVYTDERGYFMETFNEAIFQEN----VRFVQDNESMSVRGVLRGLHFQR-EKPQGKLVRVIRGEIFDVAVDLRKNSDTYGEWTGVRLSDENRREFFIPEGFAHGFLALSDECIVNYKCTELYHPEYDSGIPWDDPDIGIDWPL--DLIISEKDRNWKPLRENP----------------------",
        "2IXKA": "ATRLAIPDVILFEPRVFGDDRGFFFESYNQRAFEEAchP-VSFVQDNHSRSARGVLRGLHYQI-RQAQGKLVRATLGEVFDVAVDLRRGSPTFGQWVGERLSAENKRQMWIPAGFAHGFVVLSEYAEFLYKTTDFWAPEHERCIVWNDPELKIDWPLQDAPLLSEKDRQGKAFADA----DCFP---------------",
        "3RYKB": "veTN---DAKLLEPRLFGDDRGFFTESYNKKVLEtgV--THSFVQDNVSYseAGTIRGLHFQKNPKAQTKLIQVMQGAIYDVIVDLRKDSPTFKQWRGYILSADNHRQLLVPKGFAHGFCTLVPHTIVMYKVDEYYSADHDSGVLWNDKELAIPWPV-TSPILSDKDRILPLL--------------------------",
        "1WLTA": "FENLG-MGIILIKPKVFPDKRGFFLEVFKSEDFTKMR---PNVIQTNMSFSRKGVVRGLHYQRTPKEQGKIIFVPKGRILDVAVDVRKSSPTFGKYVKAELNEENHYMLWIPPGFAHGFQALED-SIVIYFItnEYSPPHERCISYSY----IDWPI-KEVIISDKDLQCPSLEKA----EVFD---------------",
        "1NXMA": "ARPVeiPGMLEFDIPVHGDNRGWFKENFQKEKMLP-----FF-LQNNVSFSRKNVLRGLHAE----PWDKYISVagGKVLGTWVDLREG-ETFGNTYQTVIDA--SKSIFVPRGVANGFQVLSDFVAYSYLVNDY-------FVNYADPSLDIKWENLEEAEVSEADENHPFLKDVK----PLR---------------",
        "5BUVB": "ITELNISGCYLIESPIFSDERGEFVKTHHQEIFKNF------SAEEYYSRSKNNVIRGMHFQQYPDDHNKLVFCPEGEVLDVFLDIRKDSNTYGQFMSFILNPHNRRSIFLAKGIAHGFLSMKDNTLIVCKTSTVHSPSRDSGIHWNS--FGFKWPV-ENPIISDKDRNLDCF--------------------------",
        "2PA7A": "-EN------KVINFKKIIDSRGSLVA-IEE----------FSIKRVYYIftKGEEPRGFHAH----KLEQVLVCLNGSCRVILDD---------IIQEITLD--SpvGLYVGPAVWHEMHDFSSDCVMMVLASDYYDETDYIR-------------------------------------NF-----------------",
        "4O9GB": "----MLYNVALIKFKDIADKYGHLTP-IekI---------FDIKRVYYItvDKDITRGYNS-----KLHQVLICLNGSVKIRLKI-------PDEEKIIELN--DpvGLYIGPLVWREMFDFTEGCVLLVLASeyDETDYIRNY------------------------------------FY-----------------",
        "4ZU4A": "LQMSKVKGVSLHKFHLVNDLRGNLSV-GEF----------FTPKRYFTVfvPNKEVRGEHAH----ECKQFLICVSGNCSVLVDD-------GENREEYVLDS---KGIYLPPMTWGVQYKYSKDAVLLVFASHYYDSDDYIR-------------------------------------TF-----------------"
    }
    result_dict = ap.make_master_seq_full(aln_dict, full_seqs, gold_ids, "4HN1A")

    eq_(result_dict, expected)

    # ubiquitin, tricky
    aln_dict = {
        "1NDDA": "--iKVKt--gKEIEIDIEPTDKVERIKERv--kEg-pPQQQRLIYSGKQMNDEKTAADYKi--gSVLHLVl---",
        "5CHWF": "wDLKVKm---nDFLVSv--sMTVSELKKQIAQKIGVPAFQQRLAHQTAVLQDGLTLSSLGLGp-sTVMLVVq--"
    }

    gold_ids = ["1NDDA", "5CHWF"]
    full_seqs = {
        "1NDDA": "MLIKVKTLTGKEIEIDIEPTDKVERIKERVEEKEGIPPQQQRLIYSGKQMNDEKTAADYKILGGSVLHLVLALR",
        "5CHWF": "AWDLKVKMNDFLVSVNSMTVSELKKQIAQKIGVPAFQQRLAHQTAVLQDGLTLSSLGLGPSSTVMLVVQNSSEP"
                 "LSILVRNERGHSNIYEVFLTQTVDTLKKKVSQREQVHEDQFWLSFEGRPMEDKELLGEYGLKPQCTVIKHLRL"
    }

    expected = {
        "1NDDA": "MLIKVKTLTGKEIEIDIEPTDKVERIKERVEEKEGIPPQQQRLIYSGKQMNDEKTAADYKILGGSVLHLVLALR",
        "5CHWF": "--lKVKm---nDFLVSv--sMTVSELKKQi--kIg-pAFQQRLAHQTAVLQDGLTLSSLGl---sTVMLVv---",
    }
    result_dict = ap.make_master_seq_full(aln_dict, full_seqs, gold_ids, "1NDDA")

    eq_(result_dict, expected)


